### ISSUE TITLE
ssh keys

### ISSUE THREAD

**Issue by dylancarlson** [perfect7gentleman/pg_overlay#10]
I noted github ssh pub+private keys in the repo, I hope that is intentional.  :)

**Comment by perfect7gentleman** [comment]
thanx, deleted them, these were keys for committing to github

**Comment by dylancarlson** [comment]
Cool.  You may want to scan your log for the last 1-2 months to make sure all those commits are yours (in my particular case I was looking at your chromium ebuild w/ ungoogle, et al.)

**Comment by perfect7gentleman** [comment]
i re-genereated keys anyway
