### ISSUE TITLE
www-client/chromium: chrome-binary-plugins dependency: match major version

### ISSUE THREAD

**Issue by geki-yaba** [perfect7gentleman/pg_overlay#11]
Would it be possible to update the chrome-binary-plugins dependency, so that the major version matches at least? That would be cool.

Or does the chrome-binary-plugins-58* version work with your chromium-57* versions?

Yes, I do need widevine. I will open another issue wrt widevine.
Maybe you have an idea ...

**Comment by perfect7gentleman** [comment]
nope. you need to define yourself.
