### ISSUE TITLE
www-client/chromium-57.0.2987.146: widevine does not work

### ISSUE THREAD

**Issue by geki-yaba** [perfect7gentleman/pg_overlay#12]
I installed chrome-binary-plugins-57.0.2987.133:stable and your chromium-57.0.2987.146. Both with useflag widevine enabled.

Since chrome://plugins is inaccessible, one has to open developer tools(ctrl+shift+i) and put 'navigator.plugins' into 'Console' window to show plugins. I wonder if (and how to) activate widevine for chromium. Last time I tried I had to enable widevine under chrome://plugins before it worked, IIRC.

In the console window, there is the widevine plugin listed, though amazon and skyticket do not recognize it; say that it is not found. I installed google-chrome-stable and there both services worked out-of-the-box.

Would you have any ideas what google did to chromium-57 other than that chrome://plugins stupidity?

**Comment by perfect7gentleman** [comment]
Have you tried chromium from main tree?

**Comment by geki-yaba** [comment]
Hokay, I enabled useflag proprietary-codecs and amazon video works with your version. On a second thought, skyticket - which I cannot test in forseeable future - had that error message about unsopported audio codec. So I guess widevine requires proprietary-codecs. At least for amazon video and skyticket. I better report at b.g.o, so that they at least update their useflag description. I wonder about netflix.

Though, I will not recompile to test netflix. Takes far too much time. :-)

**Comment by geki-yaba** [comment]
Just for the record: https://bugs.gentoo.org/615524
