### ISSUE TITLE
www-client/chromium[iridium]: build-resolve-undefined-macro-in-Widevine.patch fails

### ISSUE THREAD

**Issue by automorphism88** [perfect7gentleman/pg_overlay#13]
With USE=iridium, build-resolve-undefined-macro-in-Widevine.patch fails to apply. Looking at the source in /var/tmp/portage, it looks like it has already been applied.

**Comment by automorphism88** [comment]
The cloud-print-disable-in-prefs-and-component-loader.patch fails as well. Looking at the source file it's supposed to patch it looks like the code it's supposed to #ifdef out isn't there. With these two patches removed, the rest of the series applies without error.

**Comment by perfect7gentleman** [comment]
fixed
