### ISSUE TITLE
missing patchfiles for dev-lang/rust 

### ISSUE THREAD

**Issue by istitov** [perfect7gentleman/pg_overlay#14]
subj. some patches are softlinks...

rust-1.18.0-configure-no-override.patch -> /home/perfect_gentleman_007/Patches/rust/rust-1.18.0-configure-no-override.patchrust-1.18.0-no-fail-fast.patch -> /home/perfect_gentleman_007/Patches/rust/rust-1.18.0-no-fail-fast.patch

**Comment by perfect7gentleman** [comment]
Fixed
