### ISSUE TITLE
Digest verification failed for dev-util/cargo/cargo-0.19.0.ebuild

### ISSUE THREAD

**Issue by metabubble** [perfect7gentleman/pg_overlay#15]
For about 2 days, when I update my system, I get this error

>  * Digest verification failed:
>  * /var/lib/layman/pg_overlay/dev-util/cargo/cargo-0.19.0.ebuild
>  * Reason: Filesize does not match recorded size
>  * Got: 4445
>  * Expected: 4464

I figure, it needs an `ebuild cargo-0.19.0.ebuild digest`

**Comment by perfect7gentleman** [comment]
fixed by deleting
