### ISSUE TITLE
Firefox always fails

### ISSUE THREAD

**Issue by matteke-games** [perfect7gentleman/pg_overlay#16]
Hi,
So I was wondering about your gcc configuration, since everytime I try to install firefox it errors on /var/tmp/portage/www-client/firefox-55.0.3/work/firefox-55.0.3/config/recurse.mk:33 thats all the error gives....

**Comment by perfect7gentleman** [comment]
What flags, gcc do you use?
Built this version on two machines with gcc-6.4.

**Comment by matteke-games** [comment]
I use gcc-7.1.0-r1, hardened toolchain. Gcc has useflags: "cxx hardened multilib nls nptl openmp pie ssp vtv"

**Comment by perfect7gentleman** [comment]
I mean flags for firefox. Anyway hardened toolchain can cause the problem.

**Comment by matteke-games** [comment]
Oh sorry, my mistake. firefox has: bindist dbus hardened hwaccel jack pulseaudio selinux system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-sqlite

And hardened toolchain can cause it? Well I'll try to compile it with gcc-5.4.0-vanilla

**Comment by matteke-games** [comment]
Even with the vanilla compiler it still fails..

**Comment by perfect7gentleman** [comment]
i think that hardened & selinux cause that problem as i re-built FF-55.0.3 with GCC-7.2.0

**Comment by matteke-games** [comment]
Hmmm okay, since I accidentally wiped my disk today I'll just reinstall gentoo with vanilla and without selinux, thank you for your time :)
