### ISSUE TITLE
debian-patchset-57 patches for firefox-57

### ISSUE THREAD

**Issue by thrushcat** [perfect7gentleman/pg_overlay#19]
debian-patchset-57/debian-hacks/Set-program-name-from-the-remoting-name.patch and
debian-patchset-57/debian-hacks/Use-the-Mozilla-Location-Service-key-when-the-Google.patch are present in Manifest, but nothing appropriate in repository.

**Comment by perfect7gentleman** [comment]
fixed
thanx
