### ISSUE TITLE
www-client/chromium-50.0.2661.76 iridium patchset needs updating

### ISSUE THREAD

**Issue by geki-yaba** [perfect7gentleman/pg_overlay#2]
webrtc-disable-WebRTC-identity-store.patch fails: needs subfolder webrtc/
http-certificate-pinning-for-iridiumbrowser.de.patch fails: no further testing

**Comment by perfect7gentleman** [comment]
there are no Iridium and Ungoogled patches for 50-versions. I recommend you to use inox

**Comment by geki-yaba** [comment]
darn, I guessed it somehow. better than nothing.
