### ISSUE TITLE
vbox-kernel-module-src-5.2.2.tar.xz not available on mirrors

### ISSUE THREAD

**Issue by bockchristian** [perfect7gentleman/pg_overlay#20]
Trying to emerge virtualbox-modules-5.2.2, portage can't download vbox-kernel-module-src-5.2.2.tar.xz

When created with the .sh in files/, checksum mismatches. Please add a mirror to the ebuild.

(probably you just forgot to upload the file here https://dev.gentoo.org/~polynomial-c/virtualbox/ )

**Comment by perfect7gentleman** [comment]
read the related bug - https://bugs.gentoo.org/635542
