### ISSUE TITLE
Slang 2.3.2.18 -tarball not exists

### ISSUE THREAD

**Issue by andreili** [perfect7gentleman/pg_overlay#21]
On now i'm updated overlays, and after update start got:
`>>> Emerging (1 of 1) sys-libs/slang-2.3.2.18::pg_overlay
>>> Downloading 'http://distfiles.gentoo.org/distfiles/slang-2.3.2.18.tar.gz'
--2018-02-14 08:19:39--  http://distfiles.gentoo.org/distfiles/slang-2.3.2.18.tar.gz
Resolving distfiles.gentoo.org... 140.211.166.134, 156.56.247.195, 216.165.129.135, ...
Connecting to distfiles.gentoo.org|140.211.166.134|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-02-14 08:19:39 ERROR 404: Not Found.

>>> Downloading 'https://www.jedsoft.org/snapshots/slang-pre2.3.2-18.tar.gz'
--2018-02-14 08:19:39--  https://www.jedsoft.org/snapshots/slang-pre2.3.2-18.tar.gz
Resolving www.jedsoft.org... 199.180.252.227
Connecting to www.jedsoft.org|199.180.252.227|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-02-14 08:19:40 ERROR 404: Not Found.

!!! Couldn't download 'slang-2.3.2.18.tar.gz'. Aborting.`
Latest avaliable version - [slang-pre2.3.2-23.tar.gz](http://www.jedsoft.org/snapshots/)

**Comment by perfect7gentleman** [comment]
do you really need that version of slang ?

**Comment by perfect7gentleman** [comment]
updated

**Comment by andreili** [comment]
Thx!
