### ISSUE TITLE
www-client/chromium forced clang build segfaults

### ISSUE THREAD

**Issue by geki-yaba** [perfect7gentleman/pg_overlay#24]
See change to fix segfaults in gentoo bugreport[0].

[0] https://bugs.gentoo.org/650082#c22 - workaround 2 changeset 1 only

**Comment by perfect7gentleman** [comment]
honestly, i don't understand. I've built chromium-65 without any problems

**Comment by geki-yaba** [comment]
Yea, there are two variations how mksnapshot can fail. Bugfix seems to go into sys-devel/clang-6.0.0-r1.

So, this bug can be closed as soon as sys-devel/clang-6.0.0-r1 is in portage tree.
