### ISSUE TITLE
gnome-base/librsvg-2.42.2::pg_overlay failed 

### ISSUE THREAD

**Issue by RomaniukVadim** [perfect7gentleman/pg_overlay#25]
Build log: https://pastebin.com/9Sjb20yZ
Emerge info: https://pastebin.com/n6b50fpb

**Comment by perfect7gentleman** [comment]
I assume you also build it for ABI_X86_32, but it won't.

**Comment by RomaniukVadim** [comment]
Any idea how to deal with it? Except don't build with ABI_X86_32

**Comment by perfect7gentleman** [comment]
nope, expert mask that version

**Comment by RomaniukVadim** [comment]
librsvg 2.42.3 merged, close issue.
