### ISSUE TITLE
false logic of eme-free in firefox-59.0.1.ebuild in case of arm

### ISSUE THREAD

**Issue by stefson** [perfect7gentleman/pg_overlay#26]
hey there, 

I used your ebuild to see how far I would make it, when trying to compile it on an arm system. But it activates --enable-eme on arm, and the build script fails in src_configure because --enable-eme is not supported per upstream. 

If you have love for arm, and you are able to change that behavior, I'd be glad to test it.

**Comment by perfect7gentleman** [comment]
enable/disable eme is controlled by USE=" eme-free". did you disable it ?
