### ISSUE TITLE
The vaapi acceleration does not work on recent dual-card systems like Optimus-enabled Gentoo

### ISSUE THREAD

**Issue by ketetefid** [perfect7gentleman/pg_overlay#33]
The current stable version of libva, libva-intel and the related packages encounter the bug as described in https://github.com/intel/intel-vaapi-driver/issues/186 in recent hardware like Kaby Lake-Nvidia pairs. This stipulates that the user must upgrade to the latest version i.e., 2.1.0 which brings the availability of vaapi back, but at a cost: the vaapi system no longer works like before for dual-card systems and you have to almost always directly specify the vaapi device in whatever application intends to use it. For example, mpv has recently been patched for this to allow for non default device path in https://github.com/mpv-player/mpv/commit/e3e2c794efcff035615ac93f8a4cd9ab2cef4d97 which is not available in the stable mpv in Gentoo yet. Among the popular media programs, the current stable version of ffmpeg does allow this and any hardware encode/decode/transcode must mention the vaapi device.

Considering the above, the current vaapi patch for Chromium does not allow this new behavior. I have built the version in your repository and can confirm that this does not work. It seems that the patch needs to be modified to use at least /dev/dri/renderD128 by default instead of the old /dev/dri/card0. I should mention that the old fallback /dev/dri/card0 is considered legacy in the recent libva but Gentoo still uses it (stable:1.7.3). So solving this might seem complicated. At least, you could introduce a flag named nvidia which will enable the new behavior if specified.

**Comment by perfect7gentleman** [comment]
invalid

**Comment by ketetefid** [comment]
Why do you invalidate bugs so quickly? If what is said is not applicable at least you should provide an explanation why it is invalid instead of just tagging bugs to close them as soon as possible.

**Comment by perfect7gentleman** [comment]
First, you didn't specifed the package.
Second, you didn't make any response.
Third, imho, 3 days is enough to provide any information if wanted to.

**Comment by perfect7gentleman** [comment]
Are you joking, trolling or smth else?
This is not developer's repository, it's just someone's else Gentoo's overlay.
I don't develop any software, package and stuff. This is an overlay with slighly modified ebuilds from main portage tree with patches taken from different sources.
If smth doesn't work in your system, open bug in upstream's bugzilla not here.

So, the bug report is invalid. Next time open bugs if you have issues with ebuilds from this overlay.
