### ISSUE TITLE
gnome-meson.eclass could not be found by inherit()

### ISSUE THREAD

**Issue by prototype99** [perfect7gentleman/pg_overlay#34]
the error appears rather messily during emerge operations
[pg_overlay-error.log](https://github.com/perfect7gentleman/pg_overlay/files/2040027/pg_overlay-error.log)

**Comment by perfect7gentleman** [comment]
check now.
alternatively u can add gnome overlay

**Comment by prototype99** [comment]
okay yeah that done it! i already had gnome overlay added though, it specifically referenced your overlay and a package in it? but either way it's fixed so we needn't worry. thank you.
