### ISSUE TITLE
clang and screenshot use flags in www-client/firefox have no description

### ISSUE THREAD

**Issue by prototype99** [perfect7gentleman/pg_overlay#39]
pretty self explanatory, there's no description for them when i use `equery u` on it.

**Comment by perfect7gentleman** [comment]
sorry, i don't do description for added use flags.
fix for use=screenshot.

**Comment by prototype99** [comment]
any info on what the clang one does at least? but thanks all the same

**Comment by perfect7gentleman** [comment]
USE=clang if you wanna build Firefox with LLVM/Clang not GCC
