### ISSUE TITLE
app-text/goldendict-9999 patch fails with -qt5

### ISSUE THREAD

**Issue by mahdi1234** [perfect7gentleman/pg_overlay#4]
it seems patch for non-qt5 doesn't apply correctly:

```
>> Source unpacked in /var/tmp/portage/app-text/goldendict-9999/work
>>> Preparing source in /var/tmp/portage/app-text/goldendict-9999/work/goldendict-9999 ...
 * Applying goldendict-36a761108-qtsingleapplication-unbundle.patch ...

 * Failed Patch: goldendict-36a761108-qtsingleapplication-unbundle.patch !
 *  ( /usr/portage/local/layman/pg_overlay/app-text/goldendict/files/goldendict-36a761108-qtsingleapplication-unbundle.patch )
 * 
 * Include in your bugreport the contents of:
 * 
 *   /var/tmp/portage/app-text/goldendict-9999/temp/goldendict-36a761108-qtsingleapplication-unbundle.patch.out

 * ERROR: app-text/goldendict-9999::pg_overlay failed (prepare phase):
 *   Failed Patch: goldendict-36a761108-qtsingleapplication-unbundle.patch!
 * 
 * Call stack:
 *     ebuild.sh, line  133:  Called src_prepare
 *   environment, line 2778:  Called epatch '/usr/portage/local/layman/pg_overlay/app-text/goldendict/files/goldendict-36a761108-qtsingleapplication-unbundle.patch'
 *   environment, line  997:  Called die
 * The specific snippet of code:
 *               die "Failed Patch: ${patchname}!";

```
this is content of patch process

> cat /var/tmp/portage/app-text/goldendict-9999/temp/goldendict-36a761108-qtsingleapplication-unbundle.patch.out
> ***** goldendict-36a761108-qtsingleapplication-unbundle.patch *****
> PWD: /var/tmp/portage/app-text/goldendict-9999/work/goldendict-9999
> PATCH TOOL: patch -> /usr/bin/patch
> VERSION INFO:
> GNU patch 2.7.5
> Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
> Copyright (C) 1988 Larry Wall
> 
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by Larry Wall and Paul Eggert
> 
> ===================================================================
> 
> PATCH COMMAND:  patch -p0 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/usr/portage/local/layman/pg_overlay/app-text/goldendict/files/goldendict-36a761108-qtsingleapplication-unbundle.patch'
> 
> ===================================================================
> checking file goldendict.pro
> Hunk #1 FAILED at 24.
> Hunk #2 succeeded at 632 (offset 84 lines).
> 1 out of 2 hunks FAILED
> 
> patch program exited with status 1
> ===================================================================
> 
> PATCH COMMAND:  patch -p1 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/usr/portage/local/layman/pg_overlay/app-text/goldendict/files/goldendict-36a761108-qtsingleapplication-unbundle.patch'
> 
> ===================================================================
> can't find file to patch at input line 3
> Perhaps you used the wrong -p or --strip option?
> The text leading up to this was:
> --------------------------
> |--- goldendict.pro.orig	2014-11-02 12:42:07.845942253 +0800
> |+++ goldendict.pro	2014-11-02 12:44:22.965590774 +0800
> --------------------------
> No file to patch.  Skipping patch.
> 2 out of 2 hunks ignored
> 
> patch program exited with status 1
> ===================================================================
> 
> PATCH COMMAND:  patch -p2 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/usr/portage/local/layman/pg_overlay/app-text/goldendict/files/goldendict-36a761108-qtsingleapplication-unbundle.patch'
> 
> ===================================================================
> can't find file to patch at input line 3
> Perhaps you used the wrong -p or --strip option?
> The text leading up to this was:
> --------------------------
> |--- goldendict.pro.orig	2014-11-02 12:42:07.845942253 +0800
> |+++ goldendict.pro	2014-11-02 12:44:22.965590774 +0800
> --------------------------
> No file to patch.  Skipping patch.
> 2 out of 2 hunks ignored
> 
> patch program exited with status 1
> ===================================================================
> 
> PATCH COMMAND:  patch -p3 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/usr/portage/local/layman/pg_overlay/app-text/goldendict/files/goldendict-36a761108-qtsingleapplication-unbundle.patch'
> 
> ===================================================================
> can't find file to patch at input line 3
> Perhaps you used the wrong -p or --strip option?
> The text leading up to this was:
> --------------------------
> |--- goldendict.pro.orig	2014-11-02 12:42:07.845942253 +0800
> |+++ goldendict.pro	2014-11-02 12:44:22.965590774 +0800
> --------------------------
> No file to patch.  Skipping patch.
> 2 out of 2 hunks ignored
> 
> patch program exited with status 1
> ===================================================================
> 
> PATCH COMMAND:  patch -p4 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/usr/portage/local/layman/pg_overlay/app-text/goldendict/files/goldendict-36a761108-qtsingleapplication-unbundle.patch'
> 
> ===================================================================
> can't find file to patch at input line 3
> Perhaps you used the wrong -p or --strip option?
> The text leading up to this was:
> --------------------------
> |--- goldendict.pro.orig	2014-11-02 12:42:07.845942253 +0800
> |+++ goldendict.pro	2014-11-02 12:44:22.965590774 +0800
> --------------------------
> No file to patch.  Skipping patch.
> 2 out of 2 hunks ignored
> 
> patch program exited with status 1
>

**Comment by perfect7gentleman** [comment]
it means that patch is outdated. I remove from ebuild

**Comment by perfect7gentleman** [comment]
if you want to correct patch, you are welcome

**Comment by perfect7gentleman** [comment]
I modified patch. Test it.

**Comment by mahdi1234** [comment]
Perfect works now, cheers
