### ISSUE TITLE
www-client/chromium-68.0.3440.118: inox-patchset-68/0001-fix-building-without-safebrowsing.patch incomplete

### ISSUE THREAD

**Issue by geki-yaba** [perfect7gentleman/pg_overlay#41]
chrome/browser/chrome_content_browser_client.cc method at the very end needs cleaning:

python "../../build/toolchain/gcc_link_wrapper.py" --output="./chrome" -- x86_64-pc-linux-gnu-clang++ -pie -Wl,--version-script=../../build/linux/chrome.map -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--n
o-as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -Wl,-rpath-link=. -Wl,--disable-new-dtags -Wl,--export-dynamic -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -o "./chrome" -Wl,--start-group @"./chrome.rsp"  -Wl,-
-end-group   -latomic -ldl -lpthread -lrt -lX11 -lX11-xcb -lxcb -lXcomposite -lXcursor -lXdamage -lXext -lXfixes -lXi -lXrender -lXtst -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -licui18n -licuuc -licudata -lsmime3 
-lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 -lva -lcups -lz -lm -lcrypt -lxml2 -lexpat -lfontconfig -ldbus-1 -levent -lXss -lpng16 -lwebpdemux -lwebpmux -lwebp -lfreetype -ljpeg -lharfbuzz -ldrm -lXrandr -lresolv -lre2 -lsnappy 
-lpci -lasound -lpulse -lpangocairo-1.0 -lpango-1.0 -lcairo -latk-1.0 -latk-bridge-2.0 -lFLAC -lminizip -lgtk-3 -lgdk-3 -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 -lxslt -llcms2 -lopenjp2 
/usr/bin/ld.lld: error: undefined symbol: safe_browsing::SafeBrowsingService::database_manager() const
>>> referenced by chrome_content_browser_client.cc
>>>               browser/chrome_content_browser_client.o:(ChromeContentBrowserClient::GetSafeBrowsingUrlCheckerDelegate(content::ResourceContext*)) in archive obj/chrome/browser/libbrowser.a

/usr/bin/ld.lld: error: undefined symbol: safe_browsing::SafeBrowsingService::ui_manager() const
>>> referenced by chrome_content_browser_client.cc
>>>               browser/chrome_content_browser_client.o:(ChromeContentBrowserClient::GetSafeBrowsingUrlCheckerDelegate(content::ResourceContext*)) in archive obj/chrome/browser/libbrowser.a

/usr/bin/ld.lld: error: undefined symbol: safe_browsing::UrlCheckerDelegateImpl::UrlCheckerDelegateImpl(scoped_refptr<safe_browsing::SafeBrowsingDatabaseManager>, scoped_refptr<safe_browsing::SafeBrowsingUIManager>)
>>> referenced by chrome_content_browser_client.cc
>>>               browser/chrome_content_browser_client.o:(scoped_refptr<safe_browsing::UrlCheckerDelegateImpl> base::MakeRefCounted<safe_browsing::UrlCheckerDelegateImpl, scoped_refptr<safe_browsing::SafeBrowsingDatabaseManager> const&, scoped_refptr<safe_browsing::SafeBrowsingUIManager> const&>(scoped_refptr<safe_browsing::SafeBrowsingDatabaseManager> const&&&, scoped_refptr<safe_browsing::SafeBrowsingUIManager> const&&&)) in archive obj/chrome/browser/libbrowser.a
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by perfect7gentleman** [comment]
cannot confirm, works for me

**Comment by geki-yaba** [comment]
Well, that does not solve it for others, though. What I see is that out/Release/chrome.rsp is listing obj/chrome/browser/libbrowser.a before obj/components/safe_browsing/db/libdatabase_manager.a and obj/components/safe_browsing/db/libv4_local_database_manager.a. The latter define the references.

`grep -E 'database_manager|obj/chrome/browser/libbrowser.a' chrome.rsp`

So, yes linking has to fail like this. Question remains why the ordering of archives is wrong.

**Comment by geki-yaba** [comment]
So, yes, just like I said, inox patch is incomplete. See www-client/chromium/files/ungoogled-chromium-69/ungoogled-chromium/fix-building-without-safebrowsing.patch. ungoogled adjusted for upstream code; inox not. Please, test with inox next time, as subject states.

**Comment by perfect7gentleman** [comment]
> www-client/chromium/files/ungoogled-chromium-69/ungoogled-chromium/fix-building-without-safebrowsing.patch
open new issue for new version, please
