### ISSUE TITLE
www-client/firefox pageActions not worked

### ISSUE THREAD

**Issue by fedan** [perfect7gentleman/pg_overlay#47]
Hi.
page actions in urlbar not show or not worked:
![firefox_no-pageaction](https://user-images.githubusercontent.com/16284235/46143289-0493db00-c249-11e8-8eb9-f7faaa326343.png)

from gentoo:
![firefox-pageaction](https://user-images.githubusercontent.com/16284235/46143387-4fadee00-c249-11e8-8596-c9fb0e466cde.png)

**Comment by perfect7gentleman** [comment]
any clues ?

**Comment by fedan** [comment]
I removed from www-client/firefox/files/privacy-patchset-62/series remove-extensions-features.patch and commented out line 240 in firefox-62.0.2.ebuild:
```
	# Privacy-esr patches
	for i in $(cat "${FILESDIR}/privacy-patchset-$(get_major_version)/series"); do eapply "${FILESDIR}/privacy-patchset-$(get_major_version)/$i"; done
#	rm -fr browser/extensions/{activity-stream,aushelper,followonsearch,formautofill,onboarding,pdfjs,pocket,webcompat,webcompat-reporter} || die
```

It works.
Then I started deleting the extensions one by one from /usr/lib64/firefox/browser/features, except screenshots@mozilla.org.xpi
It works.

It remains to understand what extensions to keep included in remove-extensions-features.patch

**Comment by pancus** [comment]
Can we have the option to selectively enable this, pdfjs and formautofilll? [Here](https://support.mozilla.org/en-US/questions/1181551) are all the plugins and what they do. activity-stream,aushelper,followonsearch,onboarding,pocket can all go straight to hell of course.

formautofill is a strange one as (i think) it just hides the popup but you can still select the prepop'd options with arrow keys. At least with my build that's what happened.

**Comment by fedan** [comment]
In general, after multiple re-emerge, this is what happened:
in www-client/firefox/firefox-62.0.2.ebuild delete pdfjs in line 240
```
#	rm -fr browser/extensions/{activity-stream,aushelper,followonsearch,formautofill,onboarding,pdfjs,pocket,webcompat,webcompat-reporter} || die
	rm -fr browser/extensions/{activity-stream,aushelper,followonsearch,formautofill,onboarding,pocket,webcompat,webcompat-reporter} || die
```
in www-client/firefox/files/privacy-patchset-62/remove-extensions-features.patch leave pdfjs
```
diff -ur firefox-62.0.2.orig/browser/extensions/moz.build firefox-62.0.2/browser/extensions/moz.build
--- firefox-62.0.2.orig/browser/extensions/moz.build	2018-09-27 21:02:03.422667363 +0300
+++ firefox-62.0.2/browser/extensions/moz.build	2018-09-28 08:12:39.194420333 +0300
@@ -5,14 +5,8 @@
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
 DIRS += [
-    'activity-stream',
-    'aushelper',
-    'formautofill',
-    'onboarding',
     'pdfjs',
-    'screenshots',
-    'webcompat',
-    'webcompat-reporter'
+    'screenshots'
 ]
 
 # Only include mortar system add-ons if we locally enable it

```

**Comment by perfect7gentleman** [comment]
@fedan, with that modified patch and leaving pdfjs, does it work?

**Comment by fedan** [comment]
> @fedan, with that modified patch and leaving pdfjs, does it work?

yes

**Comment by perfect7gentleman** [comment]
@baconsalad 

> Can we have the option to selectively enable this, pdfjs and formautofilll?
No, only two options: with or without.

**Comment by perfect7gentleman** [comment]
@fedan, thanx. I'll correct the ebuild.

**Comment by fedan** [comment]
probably need to be added to www-client/firefox/files/privacy-patchset-62/privacy.js-1
```
pref("pdfjs.disabled", true);
```

**Comment by perfect7gentleman** [comment]
do you have drop history worked ?

**Comment by fedan** [comment]
work

**Comment by perfect7gentleman** [comment]
hmm, I don't

**Comment by fedan** [comment]
you mean the history journal?

**Comment by perfect7gentleman** [comment]
I mean drop-down menu in the address bar

**Comment by fedan** [comment]
> I mean drop-down menu in the address bar
> https://prod-cdn.sumo.mozilla.net/uploads/images/2016-08-03-23-55-00-4aba47.png

It works for me. The arrow appears on the hover.

**Comment by perfect7gentleman** [comment]
yes, it appears, but doesn't work, i.e. doesn't show anything

**Comment by fedan** [comment]
Check it Search settings https://prnt.sc/kzrsbc

**Comment by fedan** [comment]
Although this is not it

**Comment by perfect7gentleman** [comment]
> Although this is not it
yep

**Comment by fedan** [comment]
here is another check
```
browser.urlbar.maxRichResults;15
```

**Comment by perfect7gentleman** [comment]
already tried that, not helped

**Comment by perfect7gentleman** [comment]
rebuilt with Clang, it worked
