### ISSUE TITLE
Thunderbird message indexing borked with system-sqlite

### ISSUE THREAD

**Issue by baconsalad** [perfect7gentleman/pg_overlay#48]
When "system-sqlite" is enabled thunderbird is unable to generate global-messages-db.sqlite and fails with these errors

> JavaScript error: resource:///modules/gloda/datastore.js, line 1533: TypeError: this.asyncConnection is null
> JavaScript error: resource:///modules/gloda/datastore.js, line 1533: TypeError: this.asyncConnection is null
> JavaScript error: resource:///modules/gloda/datastore.js, line 1533: TypeError: this.asyncConnection is null
> JavaScript error: resource:///modules/gloda/datastore.js, line 1533: TypeError: this.asyncConnection is null
> JavaScript error: resource:///modules/gloda/datastore.js, line 1533: TypeError: this.asyncConnection is null
> JavaScript error: resource:///modules/gloda/datastore.js, line 1533: TypeError: this.asyncConnection is null
> JavaScript error: resource:///modules/gloda/datastore.js, line 1533: TypeError: this.asyncConnection is null
> JavaScript error: resource:///modules/gloda/datastore.js, line 1401: TypeError: this.asyncConnection is null

It's basically [this](https://bugzilla.redhat.com/show_bug.cgi?id=1310864) exact problem.

**Comment by perfect7gentleman** [comment]
what is the exact way to reproduce? As "Find" works for me

**Comment by baconsalad** [comment]
[Here](https://support.mozilla.org/en-US/kb/rebuilding-global-database) is the mozilla guide.

To see it fail
1. delete global-messages-db.sqlite from the profile folder
2. start tb
3. tb creates the new file but it stays at 0 bytes

**Comment by perfect7gentleman** [comment]
have you tried official ebuild?

**Comment by baconsalad** [comment]
No but I will right now.

**Comment by baconsalad** [comment]
Exact same problem with the gentoo build. Chances are nobody noticed it, I only noticed because I gave [https://github.com/gyunaev/birdtray](https://github.com/gyunaev/birdtray) a try.
