### ISSUE TITLE
www-client/firefox some errors

### ISSUE THREAD

**Issue by fedan** [perfect7gentleman/pg_overlay#49]
Hi.
not emerging with options:
1. --disable-marionette
```
mozbuild.configure.options.InvalidOptionError: '--enable-marionette' implied by 'Not Android' conflicts with '--disable-marionette' from the mozconfig
```
  [See log](https://pastebin.com/1VPcNAYH).

2. --with-pthreads
```
mozbuild.configure.options.InvalidOptionError: Unknown option: --with-pthreads
```
  [See log](https://pastebin.com/xwD4qwfy).

Now emerging without these options, while there no mistakes.

**Comment by perfect7gentleman** [comment]
fixed
