### ISSUE TITLE
www-client/firefox crash on gcc8, okay with clang7

### ISSUE THREAD

**Issue by cinch** [perfect7gentleman/pg_overlay#52]
hi and thanks for this great ebuild for firefox! i'm using it because it has PGO and the privacy patches are a nice addition. i hope upstream gentoo gets PGO too..

as a FYI: when i build with gcc 8.2, firefox crashes instantly on startup. syslog:
Jan 11 17:55:20 mango kernel: traps: firefox[14515] trap invalid opcode ip:7fcf2589e691 sp:7fffb6003330 error:0 in libxul.so[7fcf22fb3000+3f74000]

no problem with the clang use flag.

---

regarding rust: you might consider adding: 
RUSTFLAGS="-C target-cpu=native"

cheers

**Comment by perfect7gentleman** [comment]
Hi and you are welcome.
As for now Mozilla supports Clang/LLVM for building Firefox, I don't test it with GCC8. If you have patches, they are always welcomed here.
