### ISSUE TITLE
why was www-client/chromium removed?

### ISSUE THREAD

**Issue by ringoding** [perfect7gentleman/pg_overlay#53]
related commit https://github.com/perfect7gentleman/pg_overlay/commit/7938beec42ba3d0d4ba473495b18c7008a551483

**Comment by perfect7gentleman** [comment]
outdated and unmaintained.

**Comment by ringoding** [comment]
Fair enough. Thanks.

**Comment by cjosephson** [comment]
Then perhaps update the README that says this overlay has, "2 - Chromium with Inox & VA-API patches"

**Comment by perfect7gentleman** [comment]
thanx. updated.
