### ISSUE TITLE
x11-libs/cairo

### ISSUE THREAD

**Issue by fedan** [perfect7gentleman/pg_overlay#54]
Hi! You x11-libs/cairo not worked. gnome-base/librsvg breaks down because of this.
SVG files not open. System floor breaks.

**Comment by perfect7gentleman** [comment]
SVG files can be opened. Everything works.

**Comment by fedan** [comment]
I used the librsvg from the gentoo repository.
Then yes, if you use from your overlay, then there should be no problems.
