### ISSUE TITLE
app-shells/push EPREFX="${EPREFIX}"

### ISSUE THREAD

**Issue by fedan** [perfect7gentleman/pg_overlay#57]
Hi!
This line has an bug:
https://github.com/perfect7gentleman/pg_overlay/blob/ecb87369a9a82100875d159a522b37302a703fd2/app-shells/push/push-3.1-r2.ebuild#L24

See https://github.com/vaeth/mv-overlay/issues/8

**Comment by perfect7gentleman** [comment]
thanx. fixed.
