### ISSUE TITLE
firefox display :0

### ISSUE THREAD

**Issue by frstrikerman** [perfect7gentleman/pg_overlay#58]
when building firefox try to open a new window with a python script `/var/tmp/portage/www-client/firefox-66.0.2/work/firefox-66.0.2/build/pgo/profileserver.py` and fail since it doesn't have access to display `:0`
logs : http://dpaste.com/3733NT5
flags :
```[ebuild  N    ] www-client/firefox-66.0.2  USE="clang dbus eme-free gmp-autoupdate jack jit kde pulseaudio screenshot startup-notification system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-sqlite system-webp -bindist -custom-cflags -custom-optimization -debug -geckodriver -hardened -hwaccel -lto (-neon) -pgo (-selinux) -test -wayland -wifi" CPU_FLAGS_X86="avx2" L10N="-ru"```

**Comment by perfect7gentleman** [comment]
use="lto pgo"

**Comment by frstrikerman** [comment]
Sure it should fix the issue but I never used the pgo flags to start with. So there is an issue with the ebuild.
I will try and tell you if it worked

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by frstrikerman** [comment]
With this it does work, but as I said it should execute pgo stuff without the flags

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by perfect7gentleman** [comment]
pgo is required use now. is it okay?
