### ISSUE TITLE
Why Too Many Changes To Chromium Ebuild When is Going To Be Ready ?

### ISSUE THREAD

**Issue by javashin** [perfect7gentleman/pg_overlay#59]
Compilling Chromium from ebuild commit ee25096645a4334de5dfe6ec310f9800e48d17a5 is going to be more changes ?

**Comment by javashin** [comment]
i really like now the thin-jobs= are equally to makeopts on make.conf thanks for that

**Comment by javashin** [comment]
i personally add to your ebuild this : 



 # Allow building against system libraries in official builds
  sed -i 's/OFFICIAL_BUILD/GOOGLE_CHROME_BUILD/' \
    tools/generate_shim_headers/generate_shim_headers.py

  # https://crbug.com/893950
  sed -i -e 's/\<xmlMalloc\>/malloc/' -e 's/\<xmlFree\>/free/' \
    third_party/blink/renderer/core/xml/*.cc \
    third_party/blink/renderer/core/xml/parser/xml_document_parser.cc \
    third_party/libxml/chromium/libxml_utils.cc



and 

    'is_official_build=true' # implies is_cfi=true on x86_64



and 


 # https://crbug.com/949312
 chromium-glibc-2.29.patch from archlinux

**Comment by perfect7gentleman** [comment]
I can't make it work on my system.

**Comment by javashin** [comment]
i have it installed but i have to disable lto thin and optimizations i dont know whats the problem but get stuck at the end of LLD linking with -Wl,--thinlto-jobs=3 or -Wl,--thinlto-jobs=2 or like with default -Wl,--thinlto-jobs=8 without adding anything just get stuck after compile v8 snapshot and chrome and chromedriver

**Comment by javashin** [comment]
i dont think that the patches are the problem i have a successful build without thinlto and thinlto optimization and without is_official build which trigger thinlto

**Comment by javashin** [comment]
![Screenshot at 2019-04-30 07-23-34](https://user-images.githubusercontent.com/15115613/56958697-06908600-6b19-11e9-8215-e040725cf8bf.png)

**Comment by perfect7gentleman** [comment]
I can build it too. but there is permanent "Aw, snap".
so i delete it form the overlay.

**Comment by javashin** [comment]
YEah The Aw Snap Its Here Too

But I i dont care 

i use this 


#!/bin/bash
/usr/bin/chromium.bin --flag-switches-begin --test-type --disable-seccomp-filter-sandbox --enable-http-form-warning --enable-experimental-canvas-features --enable-fast-unload --javascript-harmony --enabled-new-style-notification --enable-quic --site-per-process --enable-tcp-fastopen --ignore-gpu-blacklist --save-page-as-mhtml --enable-smooth-scrolling -–enable-zero-copy -–enable-gpu-rasterization --enable-native-gpu-memory-buffers --enable-features=CheckerImaging,MaterialDesignExtensions,OmniboxDisplayTitleForCurrentUrl,OmniboxTailSuggestions,OmniboxUIExperimentShowSuggestionFavicons,OmniboxUIExperimentVerticalLayout,SecondaryUiMd --disable-features=MaterialDesignBookmarks --autoplay-policy=document-user-activation-required --enable-gpu-rasterization --ignore-gpu-blacklist --flag-switches-end
