### ISSUE TITLE
Megasync doasn't build

### ISSUE THREAD

**Issue by ensarman** [perfect7gentleman/pg_overlay#6]
> > > Emerging (5 of 5) net-misc/megasync-9999::pg_overlay
> > > Unpacking source...
> > > Initialized empty Git repository in /usr/portage/distfiles/git3-src/meganz_MEGAsync.git/
> > > - Fetching git://github.com/meganz/MEGAsync.git ...
> > >   git fetch git://github.com/meganz/MEGAsync.git +HEAD:refs/git-r3/HEAD
> > >   remote: Counting objects: 21513, done.
> > >   remote: Compressing objects: 100% (36/36), done.
> > >   remote: Total 21513 (delta 69), reused 71 (delta 58), pack-reused 21419
> > >   Receiving objects: 100% (21513/21513), 24.43 MiB | 1.13 MiB/s, done.
> > >   Resolving deltas: 100% (16922/16922), done.
> > >   From git://github.com/meganz/MEGAsync
> > > - [new ref]                    -> refs/git-r3/HEAD
> > > - [new tag]         v2_7_0_0_OSX -> v2_7_0_0_OSX
> > > - [new tag]         v2_7_0_0_Win -> v2_7_0_0_Win
> > > - [new tag]         v2_7_1_0_Linux -> v2_7_1_0_Linux
> > > - [new tag]         v2_7_1_0_OSX -> v2_7_1_0_OSX
> > > - [new tag]         v2_7_1_0_Win -> v2_7_1_0_Win
> > > - [new tag]         v2_7_2_0_Linux -> v2_7_2_0_Linux
> > > - [new tag]         v2_8_0_0_Linux -> v2_8_0_0_Linux
> > > - [new tag]         v2_8_0_0_OSX -> v2_8_0_0_OSX
> > > - [new tag]         v2_8_0_0_Win -> v2_8_0_0_Win
> > > - [new tag]         v2_9_0_0_OSX -> v2_9_0_0_OSX
> > > - [new tag]         v2_9_0_0_Win -> v2_9_0_0_Win
> > > - [new tag]         v2_9_1_0_Linux -> v2_9_1_0_Linux
> > > - [new tag]         v2_9_1_0_OSX -> v2_9_1_0_OSX
> > > - [new tag]         v2_9_1_0_Win -> v2_9_1_0_Win
> > > - [new tag]         v2_9_5_0_Linux -> v2_9_5_0_Linux
> > > - [new tag]         v2_9_5_0_OSX -> v2_9_5_0_OSX
> > > - [new tag]         v2_9_5_0_Win -> v2_9_5_0_Win
> > > - [new tag]         v2_9_6_0_OSX -> v2_9_6_0_OSX
> > > - [new tag]         v2_9_6_0_Win -> v2_9_6_0_Win
> > > - [new tag]         v2_9_8_0_Linux -> v2_9_8_0_Linux
> > > - [new tag]         v2_9_8_0_OSX -> v2_9_8_0_OSX
> > > - [new tag]         v2_9_8_0_Win -> v2_9_8_0_Win
> > >   git symbolic-ref refs/git-r3/net-misc/megasync/0/**main** refs/git-r3/HEAD
> > >   Initialized empty Git repository in /usr/portage/distfiles/git3-src/meganz_sdk.git/
> > > - Fetching https://github.com/meganz/sdk.git ...
> > >   git fetch https://github.com/meganz/sdk.git --prune +refs/heads/_:refs/heads/_ +refs/tags/_:refs/tags/_ +refs/notes/_:refs/notes/_ +HEAD:refs/git-r3/HEAD
> > >   remote: Counting objects: 28863, done.
> > >   remote: Compressing objects: 100% (171/171), done.
> > >   remote: Total 28863 (delta 103), reused 0 (delta 0), pack-reused 28692
> > >   Receiving objects: 100% (28863/28863), 13.16 MiB | 1.09 MiB/s, done.
> > >   Resolving deltas: 100% (21156/21156), done.
> > >   From https://github.com/meganz/sdk
> > > - [new branch]      add-get-chat -> add-get-chat
> > > - [new branch]      android_cross_compile_autotools_fix -> android_cross_compile_autotools_fix
> > > - [new branch]      autotools_install_proper_headers -> autotools_install_proper_headers
> > > - [new branch]      configuration_rework -> configuration_rework
> > > - [new branch]      configuration_rework_jssdk -> configuration_rework_jssdk
> > > - [new branch]      develop    -> develop
> > > - [new branch]      feature/bandwidth-valid -> feature/bandwidth-valid
> > > - [new branch]      feature/blockedfile -> feature/blockedfile
> > > - [new branch]      feature/chat-dup-notif -> feature/chat-dup-notif
> > > - [new branch]      feature/cloudraid -> feature/cloudraid
> > > - [new branch]      feature/down-public-folders_leakfix -> feature/down-public-folders_leakfix
> > > - [new branch]      feature/pausesc -> feature/pausesc
> > > - [new branch]      feature/speed-limits -> feature/speed-limits
> > > - [new branch]      feature/transfer-management -> feature/transfer-management
> > > - [new branch]      feature/whyamiblocked -> feature/whyamiblocked
> > > - [new branch]      fixgtests  -> fixgtests
> > > - [new branch]      jssdk      -> jssdk
> > > - [new branch]      malloc-free -> malloc-free
> > > - [new branch]      master     -> master
> > > - [new branch]      megacliAPI -> megacliAPI
> > > - [new branch]      megacliAPI_authorize_folders -> megacliAPI_authorize_folders
> > > - [new branch]      megacliAPI_transfers -> megacliAPI_transfers
> > > - [new branch]      nod_children -> nod_children
> > > - [new branch]      nodes_ondemand -> nodes_ondemand
> > > - [new branch]      openssl102h -> openssl102h
> > > - [new branch]      regexp     -> regexp
> > > - [new branch]      reset-system-mask -> reset-system-mask
> > > - [new branch]      upload-and-move -> upload-and-move
> > > - [new branch]      upload-from-inputstream -> upload-from-inputstream
> > > - [new branch]      use_local_dependencies -> use_local_dependencies
> > > - [new tag]         v2.5.0     -> v2.5.0
> > > - [new ref]                    -> refs/git-r3/HEAD
> > >   git update-ref --no-deref refs/git-r3/net-misc/megasync/0/src/MEGASync/mega/**main** 0ac51295c9c020e31f89d2746b31fdd3091bbd9b
> > > - Checking out git://github.com/meganz/MEGAsync.git to /var/tmp/portage/net-misc/megasync-9999/work/megasync-9999 ...
> > >   git checkout --quiet refs/git-r3/HEAD
> > >   GIT NEW branch -->
> > >   repository:               git://github.com/meganz/MEGAsync.git
> > >   at the commit:            e3985f14dfd774d416cf0642a22e39d78818e0ef
> > > - Checking out https://github.com/meganz/sdk.git to /var/tmp/portage/net-misc/megasync-9999/work/megasync-9999/src/MEGASync/mega ...
> > >   git checkout --quiet 0ac51295c9c020e31f89d2746b31fdd3091bbd9b
> > >   GIT NEW branch -->
> > >   repository:               https://github.com/meganz/sdk.git
> > >   at the commit:            0ac51295c9c020e31f89d2746b31fdd3091bbd9b
> > >   Source unpacked in /var/tmp/portage/net-misc/megasync-9999/work
> > >   Preparing source in /var/tmp/portage/net-misc/megasync-9999/work/megasync-9999 ...
> > >   Source prepared.
> > >   Configuring source in /var/tmp/portage/net-misc/megasync-9999/work/megasync-9999 ...
> > > - ERROR: net-misc/megasync-9999::pg_overlay failed (configure phase):
> > > -   no configure script found
> > > - 
> > > - Call stack:
> > > -          ebuild.sh, line  115:  Called src_configure
> > > -        environment, line 3629:  Called econf '--disable-silent-rules' '--disable-curl-checks' '--disable-megaapi' '--with-zlib' '--with-sqlite' '--with-cryptopp' '--with-cares' '--with-curl' '--without-termcap' '--disable-posix-threads' '--with-sodium' '--without-freeimage' '--with-readline' '--disable-examples'
> > > -   phase-helpers.sh, line  668:  Called die
> > > - The specific snippet of code:
> > > -          die "no configure script found"
> > > - 
> > > - If you need support, post the output of `emerge --info '=net-misc/megasync-9999::pg_overlay'`,
> > > - the complete build log and the output of `emerge -pqv '=net-misc/megasync-9999::pg_overlay'`.
> > > - The complete build log is located at '/var/tmp/portage/net-misc/megasync-9999/temp/build.log'.
> > > - The ebuild environment file is located at '/var/tmp/portage/net-misc/megasync-9999/temp/environment'.
> > > - Working directory: '/var/tmp/portage/net-misc/megasync-9999/work/megasync-9999/src/MEGASync/mega'
> > > - S: '/var/tmp/portage/net-misc/megasync-9999/work/megasync-9999'

**Comment by perfect7gentleman** [comment]
oops
sorry but megasync is not in overlay anymore
