### ISSUE TITLE
Chromium ebuild  suggestion

### ISSUE THREAD

**Issue by shelterx** [perfect7gentleman/pg_overlay#62]
Maybe the chromium ebuild should set clang and lld as required packages, it won't build without them.

**Comment by perfect7gentleman** [comment]
pull request

**Comment by jpsollie** [comment]
Same suggestion (almost the same) :
ungoogled-chromium does not compile with clang 7, suggest requesting clang 8 and lld 8 (very important, clang 8 will install with lld 7 when that one is already installed, so an upgrade to lld 8 is required)

**Comment by perfect7gentleman** [comment]
https://github.com/perfect7gentleman/pg_overlay/commit/e174547882bce3bd0974d42470b38cf510d33e2d
