### ISSUE TITLE
hello i have a problem with kwin from this overlay and qt 5.13 from here too.

### ISSUE THREAD

**Issue by javashin** [perfect7gentleman/pg_overlay#64]
https://gist.github.com/javashin/95c557f1dd830f0844fa673670ed9f21 sorry not complete

https://justpaste.it/2i6a2 complete build log

kwin is looking to link libs from /usr/lib and not /usr/lib64

if i do this dirty hack

ln -s /usr/lib64/libQt5Widgets.so /usr/lib/libQt5Widgets.so
ln -s /usr/lib64/libQt5Gui.so /usr/lib/libQt5Gui.so
ln -s /usr/lib64/libQt5Core.so /usr/lib/libQt5Core.so

mv /usr/lib/libGL.so /usr/lib/libGL.so.bak
ln -s /usr/lib64/libGL.so /usr/lib/libGL.so

compiles fine

**Comment by perfect7gentleman** [comment]
I know about that.
sed -i s:usr/lib/:usr/lib64/:g build.ninja in work directory works fine too.

**Comment by javashin** [comment]
oh you know and what other permanent solution is there about that , i get here too late i already deleted all the qt 5.13 and downgraded to the gentoo default ones 5.12.3 too bad

**Comment by javashin** [comment]
i was thinking was my system

**Comment by javashin** [comment]
but this happen to kde-frameworks/kjsembed
kde-frameworks/kross
 
too

**Comment by perfect7gentleman** [comment]
imo, it's smth with qt-5.13. i don't know what exactly as ebuilds are the same.

**Comment by perfect7gentleman** [comment]
fixed
