### ISSUE TITLE
chromium 75 compiler errors

### ISSUE THREAD

**Issue by jpsollie** [perfect7gentleman/pg_overlay#65]
- using portage profile 17.1-no-multilib on amd64, the ffmpeg-system must be set when ffmpeg 4.1 is installed, while the USE flag is not enough: the flag is hard-masked.  Adding "www-client/chromium -system-ffmpeg" to /etc/portage/profile/package.mask fixes this.
- Chromium doesn't build when using python 3.x.  I'd suggest to force it to use python 2.7
- the third_party/angle part has problems in the "common/debug.h" header.  you need to add "#include <build_tools>" into the debug.h header and cp build/build_tools.h into third_party/angle/include/ (symlink does not work)
- the base/logging.h header is invoked for a template that does not exist in the logging header (according to gcc9).  The candidate template here is at rule 712. Adding this code fixes the error, but will also disable some of the chromium logging:
`
template <typename T>
inline typename std::enable_if<
    !base::internal::SupportsOstreamOperator<const T&>::value &&
        !std::is_enum<T>::value,
    void>::type
MakeCheckOpValueString(std::ostream* os, const T& v) {
        return;
}
`
I didn't try it with another compiler, tough.  I will update this issue as soon as I have more info.
using chrome-flags:

www-client/chromium-75.0.3770.90::pg_overlay  USE="closure-compile cups custom-cflags hangouts (pic) proprietary-codecs pulseaudio suid system-ffmpeg tcmalloc vaapi widevine -component-build -gnome-keyring -jumbo-build -kerberos (-neon) (-selinux) (-system-icu) (-system-libvpx)"

**Comment by perfect7gentleman** [comment]
please, ignore this ebuild

**Comment by jpsollie** [comment]
> please, ignore this ebuild

Why? I thought I was helping you? Besides, I really like your vaapi patch! 

Btw: one last thing gcc9 did not like:
chromium/components/omnibox/browser/autocomplete_match.cc@159:
Gcc9 does not like the `noexcept = default` option, `noexcept(false) = default` does the trick

**Comment by perfect7gentleman** [comment]
Currently I don't support Chromium-75 as I accidentally updated it to 76. And I don't test ebuilds with GCC.
