### ISSUE TITLE
Thunderbird 6.8.0 fails to compile

### ISSUE THREAD

**Issue by baconsalad** [perfect7gentleman/pg_overlay#67]
Here is the error https://paste.ubuntu.com/p/QDqYGTWPBx/

I have tried with my default use flags "custom-cflags custom-optimization jit kde system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-sqlite -wifi" and disabling every use flag it still fails at the same spot.

**Comment by perfect7gentleman** [comment]
which rust and version?

**Comment by baconsalad** [comment]
dev-lang/rust-1.36.0 from gentoo

**Comment by perfect7gentleman** [comment]
Have you tried to build Thunderbird::gentoo?

**Comment by baconsalad** [comment]
gentoo compiled, roughly same use flags.

**Comment by javashin** [comment]
mail-client/thunderbird-60.8.0::pg_overlay was built with the following:
USE="custom-cflags custom-optimization dbus jit lightning pulseaudio startup-notification system-harfbuzz system-icu system-jpeg system-libevent system-sqlite wifi -bindist -clang -debug -hardened -jack -kde (-neon) (-selinux) -system-libvpx" ABI_X86="(64)" L10N="-en-GB -ru"
CFLAGS="-O3 -march=native -pipe -Wl,-O2 -Wl,--as-needed -fuse-ld=bfd -Wl,--hash-style=gnu"
CXXFLAGS="-O3 -march=native -pipe -Wl,-O2 -Wl,--as-needed -fuse-ld=bfd -Wl,--hash-style=gnu -flifetime-dse=1"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs buildpkg config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -fuse-ld=bfd -Wl,--hash-style=gnu -Wl,-rpath=/usr/lib64/thunderbird,--enable-new-dtags"

**Comment by perfect7gentleman** [comment]
```
 ~ $ emerge -avtp thunderbird

These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild   R    ] mail-client/thunderbird-60.8.0::pg_overlay  USE="custom-cflags custom-optimization dbus jit kde lightning system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-sqlite -bindist -clang -debug -hardened -jack (-neon) -pulseaudio (-selinux) -startup-notification -wifi" L10N="ru -en-GB" 0 KiB
```

**Comment by perfect7gentleman** [comment]
confirm, I can't it rebuild for now

**Comment by perfect7gentleman** [comment]
fixed
```
mail-client/thunderbird-60.8.0::pg_overlay was built with the following:
USE="custom-cflags custom-optimization dbus jit kde lightning system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-sqlite -bindist -clang -debug -hardened -jack (-neon) -pulseaudio (-selinux) -startup-notification -wifi" L10N="ru -en-GB"
CFLAGS="-march=native -mtune=native -pipe -fomit-frame-pointer -fno-plt -fno-stack-protector -ftree-vectorize -flto=9 -fuse-linker-plugin -s -fuse-ld=bfd -ffat-lto-objects"
CXXFLAGS="-march=native -mtune=native -pipe -fomit-frame-pointer -fno-plt -fno-stack-protector -ftree-vectorize -flto=9 -fuse-linker-plugin -s -fuse-ld=bfd -ffat-lto-objects -flifetime-dse=1"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--sort-common -Wl,--strip-debug -flto=9 -fuse-linker-plugin -Wl,-fuse-ld=bfd -fuse-ld=bfd -ffat-lto-objects -Wl,-rpath=/usr/lib64/thunderbird,--enable-new-dtags"
```

**Comment by baconsalad** [comment]
compiled for me as well. thanks.
