### ISSUE TITLE
www-client/ungoogled-chromium widevine loading

### ISSUE THREAD

**Issue by jpsollie** [perfect7gentleman/pg_overlay#69]
ungoogled chromium does not load widevine, but an strace showed it opens the file read-only, and gets an F_OK return, so the error must be somewhere within the chromium code.
Tried with widevine 1.4.9 (google's site) and 1.4.10 (vivaldi site)
[buildinfo.txt](https://github.com/perfect7gentleman/pg_overlay/files/3488669/buildinfo.txt)
[strace.txt](https://github.com/perfect7gentleman/pg_overlay/files/3488671/strace.txt)

**Comment by perfect7gentleman** [comment]
Sorry, I don't use widewine.
Anyway it's outdated.
