### ISSUE TITLE
rtorrent-ps fails to patch.

### ISSUE THREAD

**Issue by FrozenPigs** [perfect7gentleman/pg_overlay#7]
Here is the build log https://paste.pound-python.org/show/8JslyqIoYpPmNBDf6Vf9/ even though the problem is probably just the patches are too old for the git version of rtorrent, who knows.

**Comment by perfect7gentleman** [comment]
ps-patches have not been updated for a long time. once those patches could be applied but not now.

**Comment by perfect7gentleman** [comment]
try now
