### ISSUE TITLE
Firefox 69 fails with nss ?

### ISSUE THREAD

**Issue by javashin** [perfect7gentleman/pg_overlay#70]
84:45.14 gmake[8]: Entering directory '/var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff/browser/branding/official/locales'
84:45.14 /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff/_virtualenvs/init/bin/python -m mozbuild.action.jar_maker   -d ../../../../dist/xpi-stage/locale-en-US/browser -t /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0 -f symlink  --relativesrcdir=browser/branding/official/locales -c /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/browser/branding/official/locales/en-US --root-manifest-entry-appid='{ec8030f7-c20a-464f-9b0e-13a3a9e97384}' -DNDEBUG=1 -DTRIMMED=1 -DBROWSER_CHROME_URL=chrome://browser/content/browser.xhtml -DBROWSER_CHROME_URL_QUOTED='"chrome://browser/content/browser.xhtml"' -DBUILD_CTYPES=1 -DCROSS_COMPILE='' -DENABLE_INTL_API=1 -DENABLE_REMOTE_AGENT=1 -DENABLE_SYSTEM_EXTENSION_DIRS=1 -DEXPOSE_INTL_API=1 -DFORCE_PR_LOG=1 -DFUNCPROTO=15 -DGDK_VERSION_MAX_ALLOWED=GDK_VERSION_3_4 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -DGL_PROVIDER_EGL=1 -DHAVE_64BIT_BUILD=1 -DHAVE_ALLOCA_H=1 -DHAVE_BYTESWAP_H=1 -DHAVE_CLOCK_MONOTONIC=1 -DHAVE_CPUID_H=1 -DHAVE_DIRENT_H=1 -DHAVE_DLADDR=1 -DHAVE_DLOPEN=1 -DHAVE_FONTCONFIG_FCFREETYPE_H=1 -DHAVE_FT_BITMAP_SIZE_Y_PPEM=1 -DHAVE_FT_GLYPHSLOT_EMBOLDEN=1 -DHAVE_FT_LOAD_SFNT_TABLE=1 -DHAVE_GETOPT_H=1 -DHAVE_GETTID=1 -DHAVE_GMTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAVE_LCHOWN=1 -DHAVE_LIBPNG=1 -DHAVE_LINUX_IF_ADDR_H=1 -DHAVE_LINUX_PERF_EVENT_H=1 -DHAVE_LINUX_QUOTA_H=1 -DHAVE_LINUX_RTNETLINK_H=1 -DHAVE_LOCALECONV=1 -DHAVE_LOCALTIME_R=1 -DHAVE_LSTAT64=1 -DHAVE_MALLINFO=1 -DHAVE_MALLOC_H=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MEMALIGN=1 -DHAVE_MEMMEM=1 -DHAVE_NETINET_IN_H=1 -DHAVE_NL_TYPES_H=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_POSIX_FALLOCATE=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_PTHREAD_H=1 -DHAVE_RES_NINIT=1 -DHAVE_SETPRIORITY=1 -DHAVE_STAT64=1 -DHAVE_STDINT_H=1 -DHAVE_STRERROR=1 -DHAVE_STRNDUP=1 -DHAVE_SYSCALL=1 -DHAVE_SYS_QUEUE_H=1 -DHAVE_SYS_QUOTA_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_THREAD_TLS_KEYWORD=1 -DHAVE_TRUNCATE64=1 -DHAVE_UNISTD_H=1 -DHAVE_VALLOC=1 -DHAVE_VA_COPY=1 -DHAVE_VA_LIST_AS_ARRAY=1 -DHAVE_VISIBILITY_ATTRIBUTE=1 -DHAVE_VISIBILITY_HIDDEN_ATTRIBUTE=1 -DHAVE__UNWIND_BACKTRACE=1 -DHAVE___CXA_DEMANGLE=1 -DJS_64BIT=1 -DJS_CODEGEN_X64=1 -DJS_DEFAULT_JITREPORT_GRANULARITY=3 -DJS_PUNBOX64=1 -DMALLOC_H='<malloc.h>' -DMALLOC_USABLE_SIZE_CONST_PTR='' -DMOZILLA_UAVERSION='"69.0"' -DMOZILLA_VERSION='"69.0"' -DMOZILLA_VERSION_U=69.0 -DMOZ_APP_UA_NAME='""' -DMOZ_APP_UA_VERSION='"69.0"' -DMOZ_AV1=1 -DMOZ_BLOCK_PROFILE_DOWNGRADE=1 -DMOZ_BUILD_APP=browser -DMOZ_BUNDLED_FONTS=1 -DMOZ_DATA_REPORTING=1 -DMOZ_DEDICATED_PROFILES=1 -DMOZ_DISABLE_PARENTAL_CONTROLS=1 -DMOZ_DISTRIBUTION_ID='"org.mozilla"' -DMOZ_DLL_PREFIX='"lib"' -DMOZ_DLL_SUFFIX='".so"' -DMOZ_ENABLE_DBUS=1 -DMOZ_ENABLE_SKIA=1 -DMOZ_ENABLE_STARTUP_NOTIFICATION=1 -DMOZ_FFMPEG=1 -DMOZ_FFVPX=1 -DMOZ_FMP4=1 -DMOZ_GECKO_PROFILER=1 -DMOZ_GLUE_IN_PROGRAM=1 -DMOZ_HAS_REMOTE=1 -DMOZ_INSTRUMENT_EVENT_LOOP=1 -DMOZ_LIBAV_FFT=1 -DMOZ_LOGGING=1 -DMOZ_LTO=1 -DMOZ_MACBUNDLE_ID=org.mozilla.firefox -DMOZ_MEMORY=1 -DMOZ_OFFICIAL_BRANDING=1 -DMOZ_PEERCONNECTION=1 -DMOZ_PHOENIX=1 -DMOZ_PLACES=1 -DMOZ_PROFILER_MEMORY=1 -DMOZ_PULSEAUDIO=1 -DMOZ_RAW=1 -DMOZ_RUST_SIMD=1 -DMOZ_SAMPLE_TYPE_FLOAT32=1 -DMOZ_SANDBOX=1 -DMOZ_SCTP=1 -DMOZ_SERVICES_HEALTHREPORT=1 -DMOZ_SRTP=1 -DMOZ_STATIC_JS=1 -DMOZ_SYSTEM_ICU=1 -DMOZ_SYSTEM_SQLITE=1 -DMOZ_TREE_CAIRO=1 -DMOZ_UPDATE_CHANNEL=default -DMOZ_USER_DIR='".mozilla"' -DMOZ_VORBIS=1 -DMOZ_WAYLAND=1 -DMOZ_WEBM_ENCODER=1 -DMOZ_WEBRTC=1 -DMOZ_WEBRTC_ASSERT_ALWAYS=1 -DMOZ_WEBRTC_SIGNALING=1 -DMOZ_WEBSPEECH=1 -DMOZ_WEBSPEECH_TEST_BACKEND=1 -DMOZ_WIDGET_GTK=1 -DMOZ_X11=1 -DMOZ_XUL=1 -DNO_BUILD_REFCNT_LOGGING=1 -DNO_NSPR_10_SUPPORT=1 -DNS_PRINTING=1 -DNS_PRINT_PREVIEW=1 -DRELEASE_OR_BETA=1 -DSTATIC_JS_API=1 -DSTDC_HEADERS=1 -DTARGET_XPCOM_ABI='"x86_64-gcc3"' -DUSE_SKIA=1 -DU_USING_ICU_NAMESPACE=0 -DVA_COPY=va_copy -DXP_LINUX=1 -DXP_UNIX=1 -D_REENTRANT=1 -DXPI_NAME=locale-en-US -DAB_CD=en-US /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/browser/branding/official/locales/jar.mn
84:45.14 processing /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/browser/branding/official/locales/jar.mn
84:45.14 adding 'browser' entry to root chrome manifest appid={ec8030f7-c20a-464f-9b0e-13a3a9e97384}
84:45.14 gmake[8]: Leaving directory '/var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff/browser/branding/official/locales'
84:45.14 gmake[8]: Nothing to be done for 'tools'.
84:45.84 gmake[6]: Entering directory '/var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff/browser/locales'
84:45.84 ../../config/nsinstall -D ../../dist/linux-x86_64/xpi/
84:45.84 /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff/_virtualenvs/init/bin/python -m mozbuild.action.langpack_manifest --locales en-US --min-app-ver 69.0 --max-app-ver 69.* --app-name 'Firefox' --l10n-basedir '/var/tmp/portage/www-client/firefox-69.0/homedir/.mozbuild/l10n-central' --defines /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/toolkit/locales/en-US/defines.inc /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/browser/locales/en-US/defines.inc  --langpack-eid 'langpack-en-US@firefox.mozilla.org' --input ../../dist/xpi-stage/locale-en-US
84:45.84 /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff/_virtualenvs/init/bin/python -m mozbuild.action.zip -C ../../dist/xpi-stage/locale-en-US -x **/*.manifest -x **/*.js -x **/*.ini /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff/dist/linux-x86_64/xpi/firefox-69.0.en-US.langpack.xpi chrome localization browser manifest.json
84:45.84 gmake[6]: Leaving directory '/var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff/browser/locales'
84:45.84 gmake[4]: Nothing to be done for 'tools'.
84:49.67 gmake[1]: Entering directory '/var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff'
84:49.67 rm -f jarlog/en-US.log
84:49.67 JARLOG_FILE=jarlog/en-US.log /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff/_virtualenvs/init/bin/python /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/build/pgo/profileserver.py
84:49.67 XPCOMGlueLoad error for file /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff/dist/firefox/libxul.so:
84:49.67 /usr/lib64/firefox/libnss3.so: version `NSS_3.45' not found (required by /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff/dist/firefox/libxul.so)
84:49.67 Couldn't load XPCOM.
84:49.67 Firefox exited with code 255 during profile initialization
84:49.67 gmake[1]: *** [Makefile:195: profiledbuild] Error 255
84:49.67 gmake[1]: Leaving directory '/var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff'
84:49.67 gmake: *** [client.mk:125: build] Error 2
84:49.72 112 compiler warnings present.
 * ERROR: www-client/firefox-69.0::pg_overlay failed (compile phase):
 *   Failed to run './mach build --verbose'
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_compile
 *   environment, line 6364:  Called virtx './mach' 'build' '--verbose'
 *   environment, line 7762:  Called die
 * The specific snippet of code:
 *       [[ ${retval} -ne 0 ]] && die "Failed to run '$@'";
 * 
 * If you need support, post the output of `emerge --info '=www-client/firefox-69.0::pg_overlay'`,
 * the complete build log and the output of `emerge -pqv '=www-client/firefox-69.0::pg_overlay'`.
 * The complete build log is located at '/var/tmp/portage/www-client/firefox-69.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-client/firefox-69.0/temp/environment'.
 * Working directory: '/var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0'
 * S: '/var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0'

>>> Failed to emerge www-client/firefox-69.0, Log file:

>>>  '/var/tmp/portage/www-client/firefox-69.0/temp/build.log'

**Comment by javashin** [comment]
igloo-l440 ~ # ls  /usr/lib64/firefox/libnss3.so
/usr/lib64/firefox/libnss3.so
igloo-l440 ~ # ls -lsa /usr/lib64/firefox/libnss3.so
422 -rwxr-xr-x 1 root root 735408 Aug 13 13:50 /usr/lib64/firefox/libnss3.so
igloo-l440 ~ # file /usr/lib64/firefox/libnss3.so
/usr/lib64/firefox/libnss3.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=672f6e7b6479c9e3488ba74e4a7488cb010e6cf4, stripped


www-client/firefox-68.0.2::pg_overlay was built with the following:
USE="clang custom-cflags custom-optimization dbus geckodriver gmp-autoupdate hwaccel jit lto pgo pulseaudio screenshot startup-notification system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-sqlite system-webp wayland wifi -bindist -debug -eme-free -hardened -jack -kde (-neon) (-selinux) -system-libvpx -test" ABI_X86="(64)" CPU_FLAGS_X86="avx2" L10N="-ru"
CFLAGS="-O3 -march=native -falign-functions=32 -flto=thin -fsplit-lto-unit -fno-stack-protector -fomit-frame-pointer -fno-strict-aliasing -pipe -fstack-check"
CXXFLAGS="-O3 -march=native -falign-functions=32 -flto=thin -fsplit-lto-unit -fno-stack-protector -fomit-frame-pointer -fno-strict-aliasing -pipe -fstack-check"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs buildpkg config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
LDFLAGS="-Wl,-O2 -Wl,--as-needed,-z,now -Wl,--thinlto-jobs=3 -Wl,--lto-O2 -fuse-ld=lld -Wl,--hash-style=gnu -O3 -march=native -falign-functions=32 -flto=thin -fsplit-lto-unit -fno-stack-protector -fomit-frame-pointer -fno-strict-aliasing -pipe -fstack-check -Wl,-rpath=/usr/lib64/firefox,--enable-new-dtags -Wl,--compress-debug-sections=zlib"

**Comment by javashin** [comment]
Why , dunno .....

**Comment by perfect7gentleman** [comment]
update nss

**Comment by javashin** [comment]
????
 pwd
/mnt/gentoo/var/db/pkg/dev-libs
[javashin@hellbox-l440 /mnt/gentoo/var/db/pkg/dev-libs]$ ls nss-3.46/
BINPKGMD5       CHOST           DEPEND          HOMEPAGE        LDFLAGS         PF              RESTRICT
BUILD_TIME      CONTENTS        DESCRIPTION     INHERITED       LICENSE         PROVIDES        SIZE
CATEGORY        COUNTER         EAPI            IUSE            NEEDED          RDEPEND         SLOT
CBUILD          CXXFLAGS        environment.bz2 IUSE_EFFECTIVE  NEEDED.ELF.2    repository      USE
CFLAGS          DEFINED_PHASES  FEATURES        KEYWORDS        nss-3.46.ebuild REQUIRES

**Comment by javashin** [comment]
that ^^^^^ is not enough ? what ? firefox is asking for 3.45 ? is this ebuild reproducible for you no offense i do trust all your ebuilds , i only compile firefox from this overlay , thanks in advance

**Comment by javashin** [comment]
maybe i need to unemerge the installed firefox to not make the ebuild looks for
84:49.67 /usr/lib64/firefox/libnss3.so: version `NSS_3.45' not found (required by /var/tmp/portage/www-client/firefox-69.0/work/firefox-69.0/ff/dist/firefox/libxul.so)

**Comment by perfect7gentleman** [comment]
```
www-client/firefox-69.0::pg_overlay was built with the following:
USE="clang custom-cflags custom-optimization eme-free gmp-autoupdate hwaccel jit kde lto pgo pulseaudio system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-sqlite system-webp -bindist -debug -geckodriver -hardened -jack (-neon) -screenshot (-selinux) -startup-notification -test -wayland -wifi" CPU_FLAGS_X86="avx2" L10N="ru"
CFLAGS="-march=native -mtune=native -pipe -fomit-frame-pointer -fno-plt -fno-stack-protector"
CXXFLAGS="-march=native -mtune=native -pipe -fomit-frame-pointer -fno-plt -fno-stack-protector -stdlib=libc++"
FEATURES="fixlafiles pid-sandbox usersandbox sandbox unmerge-logs usersync preserve-libs parallel-fetch parallel-install userfetch config-protect-if-modified multilib-strict strict xattr binpkg-dostrip protect-owned network-sandbox ipc-sandbox merge-sync userpriv assume-digests sfperms distlocks ebuild-locks news unknown-features-warn binpkg-docompress binpkg-logs unmerge-orphans"
LDFLAGS="-Wl,-O2 -Wl,--as-needed -Wl,--strip-debug -fuse-ld=lld -Wl,-rpath=/usr/lib64/firefox,--enable-new-dtags -Wl,--compress-debug-sections=zlib"
```
