### ISSUE TITLE
reenable webrtc for arm

### ISSUE THREAD

**Issue by stefson** [perfect7gentleman/pg_overlay#72]
the hack to disable webrtc for arm can (and should) be removed for >=firefox-68.0: 

https://github.com/perfect7gentleman/pg_overlay/blob/master/www-client/firefox/firefox-68.0.2.ebuild#L556

https://github.com/perfect7gentleman/pg_overlay/blob/master/www-client/firefox/firefox-69.0.ebuild#L559

https://github.com/perfect7gentleman/pg_overlay/blob/master/mail-client/thunderbird/thunderbird-68.0-r2.ebuild#L558

tested by me on arm, the build passes now.

**Comment by perfect7gentleman** [comment]
agree for Firefox, but I don't get it why webtrc is needed for mail-client.

**Comment by stefson** [comment]
I haven't seen beforehand that you do in fact have custom webrtc command. Keep it to you liking, this is meant as a friendly reminder that the special case of always disable webrtc for arm is no longer needed, and therefore can be removed from the affected ebuilds.
