### ISSUE TITLE
Use -import-instr-limit to mitigate size growth from ThinLTO

### ISSUE THREAD

**Issue by stefson** [perfect7gentleman/pg_overlay#77]
I recently stumbled over `-import-instr-limit`, which is a ld flag from llvm/lld, and can be used to shave off some 15% off from binary sizes. There's an upstream patch from firefox-72.0 beta branch, which introduces that flag: 
https://hg.mozilla.org/mozilla-central/rev/749fec0af516

there's another patch needed on top of that, it takes care of the fact that gcc doesn't understand that llvm/lld specific linker flag: 
https://hg.mozilla.org/mozilla-central/rev/360910f1a154

I've tested the two patches with the firefox-71.0 ebuild from the tree, and it does indeed shave off some 10mb from libs. 

would be cool to test that with all of your lto options, but feel free to close if you're not interested.

**Comment by perfect7gentleman** [comment]
done. check.

**Comment by stefson** [comment]
cool, thanks :) want to keep this open for chatting about results?

**Comment by perfect7gentleman** [comment]
nope. I don't think there will be any.
