### ISSUE TITLE
dev-util/samurai as a replacement for dev-util/ninja

### ISSUE THREAD

**Issue by stefson** [perfect7gentleman/pg_overlay#78]
hey there, 

I just stumbled upon your dev-util/samurai ebuild, and thus the repo, where it says pure C99 + focus on simplicity, speed and portability. Great, so I jumped straight in, but it doesn't really work with me for packages yet. 

Are you working with some special tweaks on cmake eclass?

**Comment by perfect7gentleman** [comment]
> Are you working with some special tweaks on cmake eclass?

yes
