### ISSUE TITLE
waf doesn't respect MAKEOPTS

### ISSUE THREAD

**Issue by joke-junkie** [perfect7gentleman/pg_overlay#8]
Apparently waf doesn't respect MAKEOPTS set in /etc/portage/make.conf. On my machine your ebuild builds only with one job. Am I missing something or it's a minor bug? I rebuilt git by hand and passing -j <number-of-jobs> did the trick (./waf configure -j 4). Could you add the respect to MAKEOPTS to your ebuild?

**Comment by joke-junkie** [comment]
I'm sorry, I didn't mention the package.
media-video/mpv

**Comment by perfect7gentleman** [comment]
it respects MAKEOPTS
```
>>> Compiling source in /tmp/portage/media-video/mpv-9999/work/mpv-9999 ...
"/tmp/portage/media-video/mpv-9999/work/mpv-9999/waf" build --verbose --jobs=9
```

**Comment by joke-junkie** [comment]
OK, it actually does there (--jobs successfully passed to waf), but top shows only one instance of cc1 when building the ebuild (which is not the case for git clone && ./waf configure && ./waf build --jobs=4) and the ebuild runs slower.
I determined the issue incorrectly, I will close this one now.

**Comment by perfect7gentleman** [comment]
Fixed
