### ISSUE TITLE
app-office/libreoffice PYTHON_USEDEP

### ISSUE THREAD

**Issue by tslnox** [perfect7gentleman/pg_overlay#81]
Can't install libreoffice-6.4.0.3 because of this error:

!!! All ebuilds that could satisfy "=app-office/libreoffice-6.4.0.3" have been masked.
!!! One of the following masked packages is required to complete your request:
- app-office/libreoffice-6.4.0.3::pg_overlay (masked by: invalid: DEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 81, invalid: RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 81)

After some light digging I found that this non-helpful error message means there is PYTHON_USEDEP which has been, in fact, removed from Portage
On the line 156:
accessibility? ( dev-python/lxml[${PYTHON_USEDEP}] )
should be:
accessibility? ( dev-python/lxml )

After change it is no longer blocked and can be emerged.

**Comment by perfect7gentleman** [comment]
fixed
