### ISSUE TITLE
www-client/firefox-75.0 disabled Firefox Accounts

### ISSUE THREAD

**Issue by barolo** [perfect7gentleman/pg_overlay#83]
For some reason this build have enabled enterprise policies and amongst other things it has disabled Firefox Accounts/Sync, which are much needed for me.  
No other build displays such behavior, nor firefox-bin:gentoo nor ones from upstream
Checked with a clean profile too
[USE="clang cross-lto gmp-autoupdate hwaccel jit kde lto pgo pulseaudio screenshot system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-webp wayland -bindist -custom-cflags -custom-optimization -debug -eme-free -geckodriver -hardened -jack (-selinux) -startup-notification -test -thinlto -wifi" CPU_FLAGS_X86="avx2" L10N="-de -en-GB -ru" 0 KiB]

**Comment by perfect7gentleman** [comment]
Yes, you're right, Firefox Accounts are disabled, and they're disabled since several versions ago.
What do you suggest?

**Comment by barolo** [comment]
Why though, why are you forcing this, shouldn't it be behind use flag? This freaked me the hell out as it disabled Mozillas's VPN, plus sharing to other devices which I use daily, to name few

**Comment by perfect7gentleman** [comment]
> why are you forcing this?

Have you read the disclamer?

>shouldn't it be behind use flag? 

PRs are welcome.

**Comment by barolo** [comment]
You mean the post-install one? normandy tidbit? Is it related? I haven't seen anything FF Account related.

**Comment by barolo** [comment]
Just modified the policies locally.
I was just taken aback by such an intrusive hand-holding, not used to it as a longtime Gentoo user.
I don't want to sound too bitchy or unappreciative because I use and enjoy your work [ recently, removal of the spidermonkey dep. ]
Thus this can be closed I guess

**Comment by perfect7gentleman** [comment]
I mean Readme.md. FF Account is related to privacy that's why it's disabled.
Further, please, open the real bugs not complaints.
