### ISSUE TITLE
<www-client/firefox-77: Force merging of Content-Security-Policy header [patch]

### ISSUE THREAD

**Issue by shnm** [perfect7gentleman/pg_overlay#84]
> Force merging of Content-Security-Policy header r=mixedpuppy Headers that are not present in the original request but are added by two or more competing extensions are not merged, but only one of the changes is applied. Since this causes issues with privacy and security enhancing extensions trying to tighten up CSP, this introduces a special case to explicitly always merge the CSP header.

Could you consider adding this patch for your ebuild? It's gonna take quite a while till we have stable FF77.

https://bugzilla.mozilla.org/show_bug.cgi?id=1462989
https://hg.mozilla.org/mozilla-central/rev/cea45f637b49

**Comment by perfect7gentleman** [comment]
Which patch exactly?

**Comment by shnm** [comment]
The one liner at:
https://phabricator.services.mozilla.com/D63554
dl link (redirects):
https://phabricator.services.mozilla.com/D63554?download=true

**Comment by perfect7gentleman** [comment]
done. check.

**Comment by stefson** [comment]
@shnm could you please open a gentoo bug as well, so that the patch might be added to the patchset for firefox-76, and everyone is getting the benefit of using itt?
