### ISSUE TITLE
www-client/firefox-76 - mozilla-s390-bigendian.patch breaks build with USE="-system-icu" on little-endian architectures

### ISSUE THREAD

**Issue by thubble** [perfect7gentleman/pg_overlay#86]
It looks like you added a new OpenSUSE patch: "mozilla-s390-bigendian.patch". When building FIrefox with the bundled version of ICU (i.e. when building with USE="-system-icu"), this patch forces the build to include the big-endian version of the ICU data file, which doesn't exist when the build runs on a little-endian architecture (such as amd64).

OpenSUSE conditionally applies this patch on only the "s390x" and "ppc64" architectures (I'm not sure how these correspond to Gentoo architectures). This patch will need to either be removed, or conditionally applied only on little-endian architectures.

**Comment by perfect7gentleman** [comment]
check.
