### ISSUE TITLE
firefox-77.0.1 build error

### ISSUE THREAD

**Issue by baconsalad** [perfect7gentleman/pg_overlay#88]
Build error with the latest firefox. I don't have wayland use flags set either way and looking at x11-libs/gtk+ the wayland flag is not enabled.

26:26.51 /tmp/portage/portage/www-client/firefox-77.0.1/work/firefox-77.0.1/ff/instrumented/dist/include/mozilla/PresShell.h:260:24: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
26:26.51   void* __attribute__((optimize("no-lifetime-dse"))) AllocateFrame(nsQueryFrame::FrameIID aID, size_t aSize) {
26:26.51                        ^
26:26.51 /tmp/portage/portage/www-client/firefox-77.0.1/work/firefox-77.0.1/gfx/thebes/gfxPlatformGtk.cpp:120:3: error: use of undeclared identifier 'mUseWebGLDmabufBackend'
26:26.51   mUseWebGLDmabufBackend =
26:26.51   ^
26:26.51 /tmp/portage/portage/www-client/firefox-77.0.1/work/firefox-77.0.1/gfx/thebes/gfxPlatformGtk.cpp:121:29: error: use of undeclared identifier 'nsWaylandDisplay'; did you mean 'nsStyleDisplay'?
26:26.51       IsWaylandDisplay() && nsWaylandDisplay::IsDMABufWebGLEnabled();
26:26.51                             ^~~~~~~~~~~~~~~~
26:26.51                             nsStyleDisplay
26:26.51 /tmp/portage/portage/www-client/firefox-77.0.1/work/firefox-77.0.1/ff/instrumented/dist/include/mozilla/ScrollStyles.h:14:8: note: 'nsStyleDisplay' declared here
26:26.51 struct nsStyleDisplay;
26:26.51        ^
26:26.51 /tmp/portage/portage/www-client/firefox-77.0.1/work/firefox-77.0.1/gfx/thebes/gfxPlatformGtk.cpp:121:47: error: no member named 'IsDMABufWebGLEnabled' in 'nsStyleDisplay'
26:26.51       IsWaylandDisplay() && nsWaylandDisplay::IsDMABufWebGLEnabled();
26:26.51                             ~~~~~~~~~~~~~~~~~~^
26:26.51 1 warning and 3 errors generated.
26:26.51 gmake[4]: *** [/tmp/portage/portage/www-client/firefox-77.0.1/work/firefox-77.0.1/config/rules.mk:752: gfxPlatformGtk.o] Error 1
26:26.51 gmake[4]: Leaving directory '/tmp/portage/portage/www-client/firefox-77.0.1/work/firefox-77.0.1/ff/instrumented/gfx/thebes'
26:26.51 gmake[4]: *** Waiting for unfinished jobs....

[ebuild     U #] www-client/firefox-77.0.1::pg_overlay [76.0.1::pg_overlay] USE="clang custom-cflags custom-optimization dbus%* gmp-autoupdate hwaccel jit kde lto pgo pulseaudio screenshot startup-notification system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-webp thinlto -bindist -cross-lto -debug -eme-free -geckodriver -hardened -jack (-selinux) -system-libvpx -test -wayland -wifi" CPU_FLAGS_X86="-avx2" L10N="-de -en-GB -ru" 0 KiB

**Comment by telans** [comment]
Same on my end:

```
20:21.18 /var/tmp/portage/www-client/firefox-77.0.1/work/firefox-77.0.1/gfx/thebes/gfxPlatformGtk.cpp:120:3: error: use of undeclared identifier 'mUseWebGLDmabufBackend'
20:21.18 /var/tmp/portage/www-client/firefox-77.0.1/work/firefox-77.0.1/gfx/thebes/gfxPlatformGtk.cpp:121:29: error: use of undeclared identifier 'nsWaylandDisplay'; did you mean 'nsStyleDisplay'?
20:21.18 /var/tmp/portage/www-client/firefox-77.0.1/work/firefox-77.0.1/gfx/thebes/gfxPlatformGtk.cpp:121:47: error: no member named 'IsDMABufWebGLEnabled' in 'nsStyleDisplay'
```

**Comment by perfect7gentleman** [comment]
Confirm. There is issue with some patches from Fedora as they are only for wayland. Disable that patch. Try now.

**Comment by telans** [comment]
@perfect7gentleman 
```
cat: /var/tmp/portage/www-client/firefox-77.0.1/files/freebsd-patchset-77/series: No such file or directory
 * Applying Fedora's patches
 * ACCESS DENIED:  unlinkat:     /var/tmp/portage/www-client/firefox-77.0.1/files/fedora-patchset-77/mozilla-1634213.patch
rm: cannot remove '/var/tmp/portage/www-client/firefox-77.0.1/files/fedora-patchset-77/mozilla-1634213.patch': Permission denied
```
Cheers

**Comment by perfect7gentleman** [comment]
fixed

**Comment by telans** [comment]
Getting this error now:

```
31:14.97 /var/tmp/portage/www-client/firefox-77.0.1/work/firefox-77.0.1/dom/media/platforms/PDMFactory.cpp:372:39: error: no member named 'UseWaylandHardwareVideoDecoding' in 'gfxPlatformGtk'; did you mean 'CanUseHardwareVideoDecoding'?
```

**Comment by perfect7gentleman** [comment]
try now

**Comment by baconsalad** [comment]
worked for me thanks. compiled about 10ish hours ago so I don't have the last few changes.

**Comment by telans** [comment]
Works for me too, cheers

**Comment by perfect7gentleman** [comment]
use sccache for rebuilding Mozilla products
