### ISSUE TITLE
waf --jobs=num and --verbose options conflict: parallel build disabled

### ISSUE THREAD

**Issue by joke-junkie** [perfect7gentleman/pg_overlay#9]
in media-video/mpv
continuation of
#8 

I cannot run parallel build with your ebuild and now I discovered that enabling both --jobs=num and --verbose options (ebuild runs them together) makes the build run slower than with --jobs=num exclusively (38s against 4-5 minutes on my machine). The both option case also loads only 1 core.

It's just a minor annoyance, but could you check and disable --verbose if you don't need it? Or should we report it as a bug to mpv or waf upstream?

**Comment by perfect7gentleman** [comment]
as you may see my ebuild is only slightly modified version of main tree ebuild. To disable --verbose it's needed to modify eclass which is highly unpreferable.

**Comment by joke-junkie** [comment]
I see.
`# @ECLASS-VARIABLE: WAF_VERBOSE
# @DESCRIPTION:
# Set to OFF to disable verbose messages during compilation
# this is _not_ meant to be set in ebuilds
: ${WAF_VERBOSE:=ON}`

So, can I set it somewhere in the environment/config files then?

**Comment by perfect7gentleman** [comment]
>So, can I set it somewhere in the environment/config files then?

try to use it environmental vairable

**Comment by joke-junkie** [comment]
OK, I did it.
It didn't work.
Then I found a bug in waf-utils.eclass
See that file:
`: ${WAF_VERBOSE:=ON}`
this line sets `WAF_VERBOSE` to `ON` if it was unset or null.
`[[ "${WAF_VERBOSE}" ]] && _mywafconfig="--verbose"`
then this line always sets local variable `_mywafconfig` to `"--verbose"` because the test before is true whenever `WAF_VERBOSE` is set and not null, which is always true because of the default setting in eclass above.
If I replace the test with `[[ "${WAF_VERBOSE}" == ON ]]` then it actually does what it is supposed to do. I was able to add the variable to make.conf and build without the `--verbose` flag.

Problem solved. I need to report the bug to gentoo.

**Comment by perfect7gentleman** [comment]
Fixed

**Comment by perfect7gentleman** [comment]
Fixed
