### ISSUE TITLE
firefox ebuild, -thinlto has no effect

### ISSUE THREAD

**Issue by barolo** [perfect7gentleman/pg_overlay#90]
Firefox is still being built with -flto=thin and O2 on top, I can see them in llvm commands

**Comment by perfect7gentleman** [comment]
Could you be more specific?

**Comment by barolo** [comment]
About? When you have lto USE flag enabled and thinlto disabled it is still being built with -flto=thin instead of -flto=full as one would assume. You can see it in commands passed to llvm during compilation

**Comment by perfect7gentleman** [comment]
for example, about USE-flags and about:buildconfig

**Comment by barolo** [comment]
about:buildconfig doesn't show you how it was LTOed, just that it was, it also lies about -O3 being used, not the first time [ where llvm was used ]

![image](https://user-images.githubusercontent.com/1215421/87247010-5541eb80-c451-11ea-8abd-eb76759ff921.png)

`
www-client/firefox-78.0.1::pg_overlay was built with the following:
USE="clang cross-lto dbus gmp-autoupdate hwaccel jit lto openh264 pgo pulseaudio screenshot system-av1 system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-webp wayland -bindist -custom-cflags -custom-optimization -debug -eme-free -geckodriver -hardened -jack -kde (-selinux) -test -thinlto -wifi" ABI_X86="(64)" CPU_FLAGS_X86="avx2" L10N="-de -en-GB -ru"
CFLAGS="-march=native -pipe -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu --target=x86_64-unknown-linux-gnu"
CXXFLAGS="-march=native -pipe -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu --target=x86_64-unknown-linux-gnu"
FEATURES="parallel-fetch parallel-install fixlafiles config-protect-if-modified merge-sync unmerge-logs binpkg-dostrip qa-unresolved-soname-deps multilib-strict usersync protect-owned preserve-libs assume-digests noinfo binpkg-logs binpkg-docompress strict split-log unmerge-orphans cgroup pid-sandbox userpriv split-elog nodoc ebuild-locks prelink-checksums unknown-features-warn candy network-sandbox ipc-sandbox distlocks userfetch sandbox news noman usersandbox xattr sfperms"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -march=native -pipe -Wl,--hash-style=gnu -Wl,-O1 -Wl,-rpath=/usr/lib64/firefox,--enable-new-dtags --target=x86_64-unknown-linux-gnu -Wl,--compress-debug-sections=zlib"
`

**Comment by perfect7gentleman** [comment]
You've disabled custom-cflags & custom-optimization and yet complain that some CFLAGS was mot used.

**Comment by barolo** [comment]
Looks like I've misunderstood some stuff, I thought that custom stuff only applies to things pulled out of the system, make.conf, etc.
Lemme rebuild then.

**Comment by barolo** [comment]
What's the point of thinlto flag though as apparently it's the default and -thinlto changes nothing?

**Comment by perfect7gentleman** [comment]
learn ebuild and 'equery u firefox'

**Comment by barolo** [comment]
Rude, equery user doesn't explain anything, it doesn't even have thinlto. Ebuilds which provide cflags releated USEs like lto, set them up themselves

**Comment by perfect7gentleman** [comment]
Yes, equery doesn't explain anything if you don't want spend couple of minutes learning ebuild, otherwise you would understand the meaning of having USE=thinlto here.

**Comment by barolo** [comment]
Thank you for being useless, "read the fucking .ebuild" would be enough, which I did and just saw that your USEs either do nothing or fuck things up

**Comment by perfect7gentleman** [comment]
use Firefox from portage tree not from this fucking overlay and everything will be alright.
